using System.Threading.Tasks;

namespace Regard.Query.Api
{
    /// <summary>
    /// Represents a product that can be queried
    /// </summary>
    public interface IQueryableProduct
    {
        /// <summary>
        /// Creates a new query builder for this product
        /// </summary>
        IQueryBuilder CreateQueryBuilder();

        /// <summary>
        /// Registers a query built by the query builder as active for this product
        /// </summary>
        /// <param name="queryName">A name for this query. If the query already exists then </param>
        /// <param name="query">A query generated by the query builder for this product (ie, the query builder created by <see cref="CreateQueryBuilder"></see>)</param>
        Task RegisterQuery(string queryName, IRegardQuery query);

        /// <summary>
        /// Runs the query with the specified name against the database
        /// </summary>
        Task<IResultEnumerator<QueryResultLine>> RunQuery(string queryName);
    }
}
